// Offline migration from a saved runtime UI manifest. It reads a file, never the settings API,
// and never silently drops a field: anything with no build-time representation is written into
// a machine-readable loss report with the supported replacement named. A migration that
// quietly lost `sandbox-html` would be worse than one that refuses to.

import { readFileSync } from "node:fs";

export interface LossEntry {
  field: string;
  value?: string;
  reason: string;
  replacement: string;
}

export interface MigrationResult {
  portalYaml: string;
  landingYaml?: string;
  loss: { schemaVersion: 1; source: string; entries: LossEntry[] };
}

interface RuntimeManifest {
  uiId?: string;
  title?: string;
  subtitle?: string;
  institution?: string;
  institutionUrl?: string;
  logo?: string;
  favicon?: string;
  language?: string;
  colors?: Record<string, string>;
  header?: { links?: { label: string; href: string }[] };
  footer?: { groups?: { title: string; links: { label: string; href: string }[] }[] };
  features?: Record<string, { enabled?: boolean } & Record<string, unknown>>;
  landing?: { blocks?: { type: string; [key: string]: unknown }[] };
  public_extensions?: Record<string, string>;
  announcements?: { id?: string; message?: string; level?: string; from?: string; to?: string }[];
}

const UNSUPPORTED_BLOCKS: Record<string, string> = {
  "html-fragment": "a Markdown or RST prose source rendered by portal-content-v1",
  "sandbox-html":
    "a declared static-docs-v1 trusted documentation subsite on this or another origin",
};

function yamlString(value: string): string {
  return JSON.stringify(value);
}

export function migrateManifest(manifest: RuntimeManifest, sourceName: string): MigrationResult {
  const loss: LossEntry[] = [];

  if (manifest.uiId) {
    loss.push({
      field: "uiId",
      value: manifest.uiId,
      reason: "v1 has no runtime settings identity; one artifact is one site.",
      replacement: "nothing: build one artifact per site and per canonical URL",
    });
  }
  if (manifest.public_extensions) {
    for (const [key, value] of Object.entries(manifest.public_extensions)) {
      loss.push({
        field: `public_extensions.${key}`,
        value,
        reason: "Free-form runtime extension maps are not part of the closed schema.",
        replacement:
          key === "stac_catalog_url"
            ? "services.<id>.catalogUrl on a stac service"
            : "a typed service or component option, or a framework capability proposal",
      });
    }
  }

  const lines: string[] = [
    "# Generated by freva-portal-builder migrate. Review every value before use:",
    "# this is a candidate translation of a runtime manifest, not a validated site.",
    "schemaVersion: 1",
    "",
    "site:",
    `  id: ${(manifest.uiId ?? "migrated-site").toLowerCase().replace(/[^a-z0-9-]+/g, "-")}`,
    `  title: ${yamlString(manifest.title ?? "Untitled portal")}`,
  ];
  if (manifest.subtitle) lines.push(`  subtitle: ${yamlString(manifest.subtitle)}`);
  lines.push(`  language: ${yamlString(manifest.language ?? "en")}`);
  lines.push("  # Replace with the exact absolute site-base URL, including its trailing slash.");
  lines.push('  canonicalUrl: "https://portal.example.org/"');
  lines.push("  identity:");
  lines.push(
    `    logo: ${yamlString(manifest.logo ? `./assets/${basename(manifest.logo)}` : "./assets/logo.svg")}`,
  );
  lines.push(
    `    favicon: ${yamlString(manifest.favicon ? `./assets/${basename(manifest.favicon)}` : "./assets/favicon.svg")}`,
  );
  if (manifest.institution) {
    lines.push("  institution:");
    lines.push(`    name: ${yamlString(manifest.institution)}`);
    if (manifest.institutionUrl) lines.push(`    url: ${yamlString(manifest.institutionUrl)}`);
  }

  lines.push("", "theme:", "  preset: default");
  const accent = manifest.colors?.accent ?? manifest.colors?.primary;
  if (accent && /^#[0-9a-fA-F]{6}$/.test(accent)) {
    lines.push("  tokens:", `    colorAccent: ${yamlString(accent)}`);
  } else if (manifest.colors) {
    for (const [key, value] of Object.entries(manifest.colors)) {
      loss.push({
        field: `colors.${key}`,
        value,
        reason: "Theme tokens are a finite, validated set.",
        replacement: "theme.tokens, or a framework proposal for a generally useful token",
      });
    }
  }

  if (manifest.header?.links?.length || manifest.footer?.groups?.length) {
    lines.push("", "chrome:");
    if (manifest.header?.links?.length) {
      lines.push("  header:", "    enabled: true", "    links:");
      for (const link of manifest.header.links) {
        lines.push(
          `      - label: ${yamlString(link.label)}`,
          `        href: ${yamlString(link.href)}`,
        );
      }
    }
    if (manifest.footer?.groups?.length) {
      lines.push("  footer:", "    enabled: true", "    groups:");
      for (const group of manifest.footer.groups) {
        lines.push(`      - title: ${yamlString(group.title)}`, "        links:");
        for (const link of group.links) {
          lines.push(
            `          - label: ${yamlString(link.label)}`,
            `            href: ${yamlString(link.href)}`,
          );
        }
      }
    }
  }

  lines.push(
    "",
    "rendering:",
    "  profile: portal-content-v1",
    "  sources:",
    "    - root: ./content",
    "      mount: /docs/",
    "  assets:",
    "    - root: ./assets",
    "      mount: /assets/",
  );

  const services: string[] = [];
  const components: string[] = [];
  for (const [name, feature] of Object.entries(manifest.features ?? {})) {
    if (name === "databrowser") {
      services.push(
        "  dataApi:",
        "    kind: databrowser",
        "    baseUrl: /api/data",
        "    authentication: optional",
      );
      components.push(
        "  data:",
        "    kind: databrowser",
        `    enabled: ${feature.enabled === true}`,
        "    service: dataApi",
        "    route: /data/",
      );
    } else if (name === "stac") {
      const catalog = manifest.public_extensions?.stac_catalog_url ?? "/api/stac/";
      services.push("  publicCatalog:", "    kind: stac", `    catalogUrl: ${yamlString(catalog)}`);
      components.push(
        "  catalog:",
        "    kind: stac-browser",
        `    enabled: ${feature.enabled === true}`,
        "    service: publicCatalog",
        "    route: /catalog/",
      );
    } else if (name === "auth") {
      services.push("  authBroker:", "    kind: auth", "    baseUrl: /api/auth/v2");
      components.push(
        "  login:",
        "    kind: auth",
        `    enabled: ${feature.enabled === true}`,
        "    service: authBroker",
      );
    } else {
      loss.push({
        field: `features.${name}`,
        reason: "The component registry is closed; there is no entry for this feature.",
        replacement: "a framework capability proposal with schema, tests and a registry entry",
      });
    }
  }
  if (services.length) lines.push("", "services:", ...services);
  if (components.length) lines.push("", "components:", ...components);

  let landingYaml: string | undefined;
  const blocks = manifest.landing?.blocks ?? [];
  if (blocks.length) {
    const landingLines = [
      "schemaVersion: 1",
      `title: ${yamlString(manifest.title ?? "Home")}`,
      "blocks:",
    ];
    for (const block of blocks) {
      const replacement = UNSUPPORTED_BLOCKS[block.type];
      if (replacement) {
        loss.push({
          field: `landing.blocks[].${block.type}`,
          reason: "Raw and sandboxed HTML are intentionally not migrated.",
          replacement,
        });
        continue;
      }
      if (block.type === "hero") {
        landingLines.push(
          "  - type: hero",
          `    heading: ${yamlString(String(block.heading ?? manifest.title ?? "Welcome"))}`,
        );
        if (block.summary) landingLines.push(`    summary: ${yamlString(String(block.summary))}`);
      } else if (block.type === "search") {
        landingLines.push("  - type: component-search", "    component: data");
      } else if (block.type === "cards" && Array.isArray(block.items)) {
        landingLines.push("  - type: cards", "    items:");
        for (const item of block.items as { title?: string; summary?: string; href?: string }[]) {
          landingLines.push(`      - title: ${yamlString(item.title ?? "Untitled")}`);
          if (item.summary) landingLines.push(`        summary: ${yamlString(item.summary)}`);
          if (item.href) landingLines.push(`        href: ${yamlString(item.href)}`);
        }
      } else {
        loss.push({
          field: `landing.blocks[].${block.type}`,
          reason: "The landing block set is closed.",
          replacement:
            "one of hero, prose, cards, links, callout, component-link, component-search",
        });
      }
    }
    landingYaml = `${landingLines.join("\n")}\n`;
    lines.push("", "landings:", "  home:", "    path: /", "    source: ./landings/home.yaml");
  }

  for (const announcement of manifest.announcements ?? []) {
    if (announcement.from || announcement.to) {
      loss.push({
        field: `announcements.${announcement.id ?? "?"}`,
        reason:
          "A dated announcement is now selected during the build against a recorded --effective-at.",
        replacement: "announcements[].startsAt/endsAt plus a scheduled build at each boundary",
      });
    }
  }

  return {
    portalYaml: `${lines.join("\n")}\n`,
    ...(landingYaml ? { landingYaml } : {}),
    loss: { schemaVersion: 1, source: sourceName, entries: loss },
  };
}

function basename(value: string): string {
  return value.split("/").pop() ?? value;
}

export function migrateFile(path: string): MigrationResult {
  const manifest = JSON.parse(readFileSync(path, "utf8")) as RuntimeManifest;
  return migrateManifest(manifest, path.split("/").pop() ?? path);
}
