// The generated STAC adapter module (AR-006).
//
// The consumer's YAML carries *use cases* - a browser title, a logo, footer links, an access
// decision, a root intro, a link policy. This module turns them into the upstream
// configuration and, when the policy needs one, into a `preprocessSTAC` function assembled
// from framework-owned named operations. The consumer never writes JavaScript, never sees an
// upstream option name and never ships a `runtime-config.js`; the generated module is bundled
// and content-hashed like any other build output. Hash routing and the derived path prefix are
// adapter values, not schema fields: they are what make a reload of
// `/catalog/#/collections/x` land on the generated component route rather than needing an SPA
// fallback from the host.

import type { StacOptions } from "../../model/types.js";

export interface StacAdapterInput {
  options: StacOptions;
  /** Materials-relative entry, resolved to a public URL by the caller. */
  entryUrl: string;
  /** Public URLs of the stylesheets the prepared application needs. */
  styleUrls: string[];
  /** The element id the prepared patch set mounts into. */
  mountId: string;
}

/**
 * The named transforms the adapter is allowed to compose. Each is a pure function over one
 * STAC document; there is no place for a consumer expression.
 */
export const NAMED_TRANSFORMS = [
  "canonicalizeAdvertisedRoot",
  "hideRelations",
  "projectRootPresentation",
] as const;

export function generateAdapterModule(input: StacAdapterInput): string {
  const { options } = input;
  const config = {
    catalogUrl: options.catalogUrl,
    catalogTitle: options.chrome.title ?? "Catalog",
    ...(options.chrome.imageUrl ? { catalogImage: options.chrome.imageUrl } : {}),
    // `url`, and not `href`. The schema field is `href`, because every other link a deployment
    // writes in this portal's YAML is `href` and a configuration format should not change
    // spelling per component. Upstream renders these as `<a :href="link.url">` and keys the
    // list on `link.url`, so handing it `href` binds `undefined` to the attribute and emits an
    // anchor WITHOUT one: underlined text that looks like a link, carries `target="_blank"`
    // and does nothing when pressed.
    footerLinks: options.chrome.footerLinks.map((link) => ({ label: link.label, url: link.href })),
    allowExternalAccess: options.access.externalCatalogs !== "deny",
    allowedDomains: [],
    // Read by the patched `basemaps.config.js`, which keeps only the layers whose origin
    // appears here. Empty means the map draws the footprint over blank ground and makes no
    // third-party request - the default, and the only behaviour a deployment gets without
    // saying otherwise. The same list becomes `img-src` in the host policy, so the map cannot
    // be configured to draw tiles the policy would refuse.
    allowedBasemapOrigins: options.access.basemapOrigins,
    historyMode: options.historyMode,
    pathPrefix: options.pathPrefix,
    showKeywordsInItemCards: false,
    showThumbnailsAsAssets: false,
  };

  const hidden = options.linkPolicy.hiddenRelations;
  const canonicalize = options.linkPolicy.canonicalizeAdvertisedRoot;
  const aliases = options.linkPolicy.rootAliases ?? [];
  // Presentation only, and only the values a deployment actually stated. `introHtml` is NOT
  // here: the introduction is portal-owned markup rendered by the portal's own content
  // pipeline into a region of the route document, and passing it through upstream would mean
  // passing rendered HTML through its CommonMark renderer.
  const rootPage = {
    ...(options.rootPage.title ? { title: options.rootPage.title } : {}),
    ...(options.rootPage.description !== undefined
      ? { description: options.rootPage.description }
      : {}),
    ...(options.rootPage.keywords ? { keywords: options.rootPage.keywords } : {}),
    ...(options.rootPage.license ? { license: options.rootPage.license } : {}),
    ...(options.rootPage.providers ? { providers: options.rootPage.providers } : {}),
    // A configured introduction replaces the drawn description - the API's and the
    // deployment's own - so the two do not appear as duplicate copy one above the other.
    // `description` is still carried: it is the route's meta description, resolved from
    // configuration and never from this document.
    ...(options.rootPage.introHtml ? { suppressDescription: true } : {}),
  };

  return `// Generated by @freva-org/portal-builder. Do not edit; it is not deployment-owned.
// Every value below comes from validated portal configuration, and the two
// transforms are framework-owned named operations, not consumer code.
const CONFIG = ${JSON.stringify(config, null, 2)};
const HIDDEN_RELATIONS = ${JSON.stringify(hidden)};
const CANONICALIZE_ROOT = ${JSON.stringify(canonicalize)};
const ROOT_ALIASES = ${JSON.stringify(aliases)};
const ROOT_PAGE = ${JSON.stringify(rootPage)};
const MOUNT_ID = ${JSON.stringify(input.mountId)};
const ENTRY_URL = ${JSON.stringify(input.entryUrl)};
const STYLE_URLS = ${JSON.stringify(input.styleUrls)};

/** The URL a loaded document says it is, which is what identifies it. */
function documentSelfUrl(loaded) {
  if (!loaded || !Array.isArray(loaded.links)) return undefined;
  for (const link of loaded.links) {
    if (link && link.rel === "self" && typeof link.href === "string") {
      try {
        return new URL(link.href, document.baseURI);
      } catch {
        return undefined;
      }
    }
  }
  return undefined;
}

/**
 * The configured catalogue, as an absolute URL.
 *
 * A deployment states its catalogue the way it states every other portal URL - \`/api/.../stac/\` -
 * and upstream is handed that string verbatim. It resolves it for its own fetches, so the catalogue
 * loads and everything looks right; what it CANNOT do with a relative string is recognise that an
 * advertised absolute link is inside the same catalogue. The consequence was visible only on a
 * catalogue that advertises absolute children: their links rendered as raw hrefs instead of browse
 * routes, and clicking one produced \`#/http://host/...\` - a dead route inside the application.
 *
 * \`document.baseURI\` is the portal document's own base - the shell writes a base element where a base
 * path applies - so this is the same absolute URL the browser would compute for any other href on
 * the page. Resolving at runtime rather than baking an absolute URL into the artifact keeps the
 * build portable: the same bytes serve every host the deployment is published to.
 */
function catalogHref() {
  try {
    return new URL(CONFIG.catalogUrl, document.baseURI).href;
  } catch {
    // A value the URL parser refuses is passed through unchanged rather than replaced by a guess;
    // upstream then fails to load a catalogue, which is the visible failure.
    return CONFIG.catalogUrl;
  }
}

/** The configured catalogue root, and every root this deployment DECLARED to be the same one. */
function rootUrls() {
  const urls = [];
  for (const candidate of [catalogHref(), ...ROOT_ALIASES]) {
    try {
      urls.push(new URL(candidate, document.baseURI));
    } catch {
      /* a URL that will not parse cannot match anything */
    }
  }
  return urls;
}

const strip = (path) => path.replace(/\\/+$/, "");

/**
 * Do two URLs carry the same query?
 *
 * Compared as parameters, not as text. \`?visible_collections=a,b\` and \`?visible_collections=a%2Cb\`
 * are the same query - the second is what the application sends after the first has been through a
 * URL library once - and comparing the raw strings called them two different catalogues, which
 * quietly made the configured root unrecognisable and rendered every view as a child. Order is not
 * significant either: a client or a proxy is free to reorder parameters.
 */
function sameQuery(a, b) {
  const normalize = (search) =>
    [...new URLSearchParams(search)]
      .map(([key, value]) => encodeURIComponent(key) + "=" + encodeURIComponent(value))
      .sort()
      .join("&");
  return normalize(a.search) === normalize(b.search);
}

/** Is \`url\` this catalogue's root, by origin, path and query? */
function matchesRoot(url) {
  for (const root of rootUrls()) {
    if (url.origin !== root.origin) continue;
    if (strip(url.pathname) !== strip(root.pathname)) continue;
    // Query is compared rather than ignored: a catalogue distinguished only by its query - the
    // visible-collections form this portal actually deploys - is a different catalogue.
    if (!sameQuery(url, root)) continue;
    return true;
  }
  return false;
}

/**
 * Rewrite the root, and anything beneath a DECLARED alias, to the public catalogue URL.
 *
 * Two things this deliberately does not do. It does not guess that an unlisted origin is an alias:
 * doing so could turn a genuine external link into a trusted local one. And it resolves each link
 * against the document that supplied it - via that document's own \`self\` - rather than against the
 * portal page, which is a different URL entirely and the wrong base for a relative href.
 */
function canonicalizeAdvertisedRoot(doc) {
  if (!CANONICALIZE_ROOT || !doc || !Array.isArray(doc.links)) return doc;
  let configured;
  try {
    configured = new URL(catalogHref(), document.baseURI);
  } catch {
    return doc;
  }
  const base = documentSelfUrl(doc) ?? new URL(document.baseURI);
  const aliases = rootUrls().slice(1);
  for (const link of doc.links) {
    if (!link || typeof link.href !== "string") continue;
    let candidate;
    try {
      candidate = new URL(link.href, base);
    } catch {
      continue;
    }
    if (matchesRoot(candidate)) {
      link.href = configured.href;
      continue;
    }
    // A descendant of a declared alias becomes the same descendant of the public root.
    for (const alias of aliases) {
      if (candidate.origin !== alias.origin) continue;
      const prefix = \`\${strip(alias.pathname)}/\`;
      if (!candidate.pathname.startsWith(prefix)) continue;
      const rest = candidate.pathname.slice(prefix.length);
      const target = new URL(configured.href);
      target.pathname = \`\${strip(configured.pathname)}/\${rest}\`;
      target.search = candidate.search;
      target.hash = candidate.hash;
      link.href = target.href;
      break;
    }
  }
  return doc;
}

/** Hide selected link relations in this browser presentation only. */
function hideRelations(doc) {
  if (HIDDEN_RELATIONS.length === 0 || !doc || !Array.isArray(doc.links)) return doc;
  doc.links = doc.links.filter((link) => !link || !HIDDEN_RELATIONS.includes(link.rel));
  return doc;
}

/**
 * Tell the page which view it is looking at.
 *
 * The portal owns a root-introduction region in the route document, and it must appear at the root
 * view and nowhere else - across normal navigation, a deep link, a hash change, back and forward,
 * and a reload.
 *
 * The first attempt read this off the document being preprocessed, on the reasoning that every view
 * loads its document through here. It does - but so does every OTHER document the view needs. The
 * root catalogue page loads the root and then each child collection for its listing, so the last
 * call before paint described a collection and the root was reported as a child: the introduction
 * never appeared at all. A document says what IT is; it does not say which one is on screen.
 *
 * Which one is on screen is the route, and the route is not a guess: \`historyMode\` and
 * \`pathPrefix\` are values this adapter derives and hands to upstream, so reading them back is
 * reading this portal's own configuration rather than reverse-engineering upstream's router.
 *
 * \`rootConfirmed\` is the document's remaining contribution: the introduction is shown only once a
 * document that really is the configured root has been loaded, so a portal pointed at a catalogue
 * that does not answer shows an error rather than an introduction over one. It never goes back to
 * false, so back and forward do not make the region flicker.
 */
let rootConfirmed = false;

function atRootRoute() {
  const location = window.location ?? {};
  if (CONFIG.historyMode === "hash") {
    // The application's own path lives in the fragment, and it carries a query of its own: the root
    // route is \`#/?visible_collections=...\` on the deployment that filters its catalogue. Only the
    // path part decides which view this is.
    const hash = String(location.hash ?? "").replace(/^#/, "");
    const path = hash.split("?")[0].split("#")[0];
    return path === "" || path === "/";
  }
  return strip(String(location.pathname ?? "")) === strip(CONFIG.pathPrefix);
}

/**
 * The attribute is set on the root element rather than on the region, so the region can be styled
 * from the stylesheet and the signal survives the region not existing at all. It is absent until
 * the first document has been loaded, and the region ships hidden, so a deep link to an item never
 * flashes the catalogue's introduction before hiding it.
 */
function publishView() {
  const element = document.documentElement;
  if (!element) return;
  const value = rootConfirmed && atRootRoute() ? "root" : "child";
  // Only on a change: this is called from a render observer, and an unnecessary attribute write is
  // a style invalidation on the root element.
  if (element.dataset.portalStacView !== value) element.dataset.portalStacView = value;
}

/*
 * When to look again.
 *
 * A navigation inside the application loads no new document when it already has one cached, so the
 * preprocessor cannot be the only trigger. Back and forward raise \`popstate\`; a bare fragment
 * change raises \`hashchange\`. A forward navigation raises NEITHER, because upstream's router -
 * like every Vue Router application, in hash mode too - navigates with \`history.pushState\`, which
 * fires no event by design.
 *
 * The remaining honest signal is that the application re-rendered, so the third trigger is a
 * MutationObserver over the mount. It is deliberately not a patched \`history.pushState\`: that is a
 * global belonging to the page, upstream and the portal would both be writing to it, and a wrapper
 * installed by a component is exactly the kind of action-at-a-distance this integration is meant to
 * avoid. The callback compares two strings and writes nothing unless the view actually changed.
 */
let viewObserver;

function watchView(host) {
  if (typeof window !== "undefined" && typeof window.addEventListener === "function") {
    window.addEventListener("hashchange", publishView);
    window.addEventListener("popstate", publishView);
  }
  if (viewObserver || typeof MutationObserver !== "function" || !host) return;
  viewObserver = new MutationObserver(publishView);
  viewObserver.observe(host, { childList: true, subtree: true });
  // The observer belongs to this document. The portal has no client router, so leaving the route is
  // a full page load - but a bfcache restore is not, and an observer left running against a
  // detached tree is the leak this releases.
  if (typeof window !== "undefined" && typeof window.addEventListener === "function") {
    window.addEventListener(
      "pagehide",
      () => {
        viewObserver?.disconnect();
        viewObserver = undefined;
      },
      { once: true },
    );
  }
}

/**
 * Portal-owned presentation of the ROOT catalogue, applied to nothing else.
 *
 * Every value comes from validated portal configuration. This changes what this portal displays; it
 * does not modify, and does not claim to modify, the remote STAC API - a licence or provider stated
 * here is this deployment's presentation of the catalogue, not an assertion the API makes.
 */
function projectRootPresentation(doc, isRoot) {
  if (!isRoot || !doc) return doc;
  if (ROOT_PAGE.title) doc.title = ROOT_PAGE.title;
  /*
   * An introduction, where there is one, IS the description in the view - so the field is emptied
   * even when a description is stated. Stating both is normal and correct: the introduction is the
   * rendered figure and prose a reader sees, the description is the one-line summary that goes in
   * the page's meta tag and into a search result. Drawn together they were the same claim twice,
   * the second time in smaller type directly under the first.
   */
  if (ROOT_PAGE.suppressDescription) doc.description = "";
  else if (ROOT_PAGE.description !== undefined) doc.description = ROOT_PAGE.description;
  if (ROOT_PAGE.keywords) doc.keywords = [...ROOT_PAGE.keywords];
  if (ROOT_PAGE.license) doc.license = ROOT_PAGE.license;
  if (ROOT_PAGE.providers) doc.providers = ROOT_PAGE.providers.map((p) => ({ ...p }));
  return doc;
}

export function preprocessSTAC(doc) {
  const self = documentSelfUrl(doc);
  /*
   * A document with no \`self\` link is the root only if it is a Catalog with no parent. Anything
   * with a parent is below the root by definition, which is the conservative reading: a false
   * negative hides an introduction, a false positive puts root metadata on a collection.
   */
  const isRoot = self
    ? matchesRoot(self)
    : Boolean(
        doc &&
          doc.type === "Catalog" &&
          Array.isArray(doc.links) &&
          !doc.links.some((link) => link && link.rel === "parent"),
      );
  if (isRoot) rootConfirmed = true;
  publishView();
  return projectRootPresentation(hideRelations(canonicalizeAdvertisedRoot(doc)), isRoot);
}

/**
 * A portal-published URL, resolved against the document that is actually serving it.
 *
 * \`catalogImage\` is baked into CONFIG as the portal publishes it - root-relative, content-hashed,
 * e.g. "/identity/stac-mark-<hash>.png". Upstream receives that string and resolves it in its own
 * context, which is not necessarily this document's: under a base path, in a local preview served
 * from a subdirectory, or anywhere the value reaches upstream as document-relative, a root-relative
 * href points somewhere the portal never published anything and the header image renders with a src
 * that 404s.
 *
 * \`document.baseURI\` is the portal document's own base - the shell writes a <base> where a base
 * path applies - so this produces the same absolute URL the browser would use for any other href in
 * the page. Already-absolute values pass through unchanged, which is what makes it safe to apply
 * unconditionally.
 */
function resolveAgainstDocument(url) {
  if (typeof url !== "string" || url === "") return undefined;
  try {
    return new URL(url, document.baseURI).href;
  } catch {
    // A value the URL parser refuses is not made better by shipping it: upstream falls back to the
    // catalogue title when there is no image, which is the controlled failure.
    return undefined;
  }
}

export function stacConfig() {
  const config = { ...CONFIG, preprocessSTAC, catalogUrl: catalogHref() };
  if ("catalogImage" in config) {
    const resolved = resolveAgainstDocument(config.catalogImage);
    if (resolved) config.catalogImage = resolved;
    else delete config.catalogImage;
  }
  return config;
}

/**
 * Upstream reads its configuration once, while its entry module is first
 * evaluated, and the patched entry mounts into an element that must already
 * exist. Both facts are load-order requirements, not preferences.
 */
export async function mountStacBrowser() {
  const host = document.getElementById(MOUNT_ID);
  if (!host) return;
  watchView(host);
  // The prepared application's own stylesheet, added once. The portal generates
  // this route's document itself, so upstream's index.html - and its script and
  // link tags - are deliberately not part of the prepared materials.
  for (const href of STYLE_URLS) {
    if (document.querySelector('link[rel="stylesheet"][href="' + href + '"]')) continue;
    const link = document.createElement("link");
    link.rel = "stylesheet";
    link.href = href;
    document.head.append(link);
  }
  window.STAC_BROWSER_CONFIG = stacConfig();
  if (window.STAC_BROWSER_INIT) {
    await window.STAC_BROWSER_INIT();
    return;
  }
  await import(/* @vite-ignore */ ENTRY_URL);
}
`;
}

/** The upstream path prefix is derived, never configured (AR-006). */
export function derivePathPrefix(basePath: string, route: string): string {
  const base = basePath.endsWith("/") ? basePath.slice(0, -1) : basePath;
  const joined = `${base}${route}`;
  return joined.endsWith("/") ? joined : `${joined}/`;
}
