#!/usr/bin/env bash
# Resolve the base images this Dockerfile builds on to immutable digests and
# record them in base-images.lock.
#
# This script is the only sanctioned way to populate that lock file. A digest is
# an observation, not a decision: it must come from a registry, and writing one
# by hand -- or guessing one -- produces a file that looks authoritative and is
# not. Run this on a machine with registry access and commit the result.
#
#   container/portal-builder/resolve-base-digests.sh
#
# Requires: docker (or podman via DOCKER=podman) with pull access to the
# configured registry.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
lock="$here/base-images.lock"
docker="${DOCKER:-docker}"

# The tags to resolve. Changing a tag here is a reviewed decision; changing the
# digest is not a decision at all, it is whatever the registry answers.
build_tag="${PORTAL_BUILDER_NODE_BUILD_TAG:-node:24.13.0-bookworm}"
runtime_tag="${PORTAL_BUILDER_NODE_RUNTIME_TAG:-node:24.13.0-bookworm-slim}"

resolve() {
  local tag="$1" reference
  "$docker" pull --quiet "$tag" >/dev/null
  reference="$("$docker" image inspect --format '{{index .RepoDigests 0}}' "$tag")"
  case "$reference" in
    *@sha256:*) ;;
    *)
      echo "resolve-base-digests: $tag did not yield a digest reference" >&2
      exit 1
      ;;
  esac
  printf '%s\n' "$reference"
}

build_reference="$(resolve "$build_tag")"
runtime_reference="$(resolve "$runtime_tag")"

umask 022
{
  echo "# Generated by container/portal-builder/resolve-base-digests.sh."
  echo "# Do not edit by hand. Every value here is a registry observation."
  echo "PORTAL_BUILDER_NODE_BUILD_IMAGE=$build_reference"
  echo "PORTAL_BUILDER_NODE_RUNTIME_IMAGE=$runtime_reference"
} > "$lock"

echo "wrote $lock"
cat "$lock"
